### PR TITLE
GRBTransientMetric

### PR DESCRIPTION
**Pull request by ebellm**
In response to Issue #30.

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
Sorry we have been so slow to respond to this. We'll work to improve our PR response time! 
Looks good.

**Comment by rhiannonlynne** [comment]
Wrong button.

**Comment by ebellm** [comment]
Hi @rhiannonlynne--did this merge somehow get reverted?  I don't see the relevant code in the current master...

**Comment by rhiannonlynne** [comment]
Oh gak.Someone merged to master recently, and who knows if they did a force
push.
I'll try to investigate.

**Comment by rhiannonlynne** [comment]
It was a force-push to master. I believe we have recovered, but if anyone has a commit between Apr 5 and Apr 9 (after a867b32132b68199d64a72a9389692f3c5d4533d) they will need to redo that, I'm afraid.

**Comment by rhiannonlynne** [comment]
Master is now force-push protected.

**Pull request merged**
