### PR TITLE
Rotational Dither Stacker

### PR DESCRIPTION
**Pull request by humnaawan**
Added a stacker that adds rotational dithers using the same rotational dithering strategy as implemented in the afterburner used for DC1 simulations ([here](https://github.com/humnaawan/sims_operations/blob/master/tools/schema_tools/prep_opsim.py)): random rotational dither after every filter change. Notebook checks to ensure the stacker is working.

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
Hi @humnaawan this is great! 
I'm sorry to add a further request though -- but given that the altScheduler, featureBasedScheduler plus the new version of Opsim (Opsim v4) use degrees for all angles, can you add a kwarg to the stacker called "degrees" (which is True if angles are in degrees, False if not) and then use that throughout the stacker to interpret the data from the database (and return values in the same units)? 
That way, your stacker will be able to be used with v3 and with v4. 
Actually -- If you don't want to implement this or don't have time, I could approve this PR and just do it myself, if that's preferable.

**Comment by rhiannonlynne** [comment]
Eh - It's okay, I'll add that myself :)

**Comment by rhiannonlynne** [comment]
Okay - I'm trying to rewrite this a little and put it into sims_maf core set of stackers, and I realize there are a few problems. 

The max rotTelPos is +90/-90, but with this random dither stacker, you risk going further than this value because there is no check that the rotTelPos is within this range after adding the random value.

How do you want to handle this?

**Comment by humnaawan** [comment]
Can we do something similar to the `wrapRA` function for translational dithers? So essentially something like:

`
def wrapTelPos(telpos):
    """
    Wraps telpos values into +90/-90
    """
`

 and adding 

` 
simData['randomDitherPerFilterChangeRotTelPos']= wrapTelPos(simData['randomDitherPerFilterChangeRotTelPos']) 
`

before returning the added column.

p.s. sorry I didnt see your comment from last night. please let me know if you'd like to make the updates.

**Comment by rhiannonlynne** [comment]
Not really - the wrapRA just translates angles > 360 degrees into the range 0-360. For the camera rotator, there really is a range of angles it just can't move into -- for example, 180 degrees is impossible. 
The easy option would be to terminate the distribution at 90 (more like what we do with the declination), but I worry that this would result in a buildup of extra observations with rotTelPos at +90/-90 degrees.  
In practice, this may not be such a big effect, but maybe what you'd really want to do is if you hit the max, then start to wander back by reducing the actual rotTelPos values.

**Comment by rhiannonlynne** [comment]
I think this is an example of where a stacker fails, in comparison with properly programming in the rotTelPos into the scheduler.

**Comment by rhiannonlynne** [comment]
Oh - and yes, I've made updates. I merged this change into sims_maf_contrib, but I will make another update to remove it from here and put the stacker into sims_maf itself. 
I've added a unit test as well, to make sure that everything is working properly.

**Comment by humnaawan** [comment]
Ah I see. How's this handled in OpSim?

We could do an iterative thing where we draw random dither offset until we get a dithered rot angle within the range?

**Comment by rhiannonlynne** [comment]
You could, but at some point if you hit 90 degrees for rotTelPos, no dither offset is going to work.

Opsim handles this by not accepting targets which would make the rotTelPos go past the limits -- it just chooses other fields to observe.

**Comment by rhiannonlynne** [comment]
I've added a version of the rotational dither stacker to MAF - https://github.com/lsst/sims_maf/pull/131 
I don't think you can comment on the PR directly (github permissions problem), but please let me know if you have any comments or questions -- I'll have a look for them here. 
Once it's approved as part of sims_maf, I'll delete the stacker from sims_maf_contrib and update the notebook accordingly.

**Comment by humnaawan** [comment]
Oh but the dither can be +/- from the original position, so wont that address being stuck at 90deg? Also, I had thought that the rotator resets after every filter change, and since we have a different random dither, we have some wiggle room in terms of at least +/-.

> Opsim handles this by not accepting targets which would make the rotTelPos go past the limits -- it just chooses other fields to observe.

Thanks!

**Comment by rhiannonlynne** [comment]
Yes- I don't think it will get "stuck" at 90 degrees, just that you will be more likely to have 90 degrees in the dithered rot tel pos values than you would before the dithering. You still may not have any values at the limits. 

Example: 

filter = g, g, r, r, r, g
rotTelPos = 0, 10, 0, 80, 90, 0
(random offsets to rotTelPos added at filter change (g->r) == 30 deg,  (r->g) == -10)
dithered values = 0, 10, 30, 90, 90, -10

I am not sure it will really be a problem in practice, just that it's something to keep in mind.

**Comment by humnaawan** [comment]
Ah I see. I guess we can make it a terminated distribution for now, and keep this issue in mind when checking for other rotational dither schemes.

**Pull request merged**
